title:              My Portfolio
email:              himonabh@gmail.com
description:        Data Analyst
author:             gothboifricc
baseurl:            "/my-portfolio-test"
url:                "https://gothboifricc.github.io"

# Social Profiles
twitter_username:   goofy
github_username:    goofy
facebook_username:  goofy
instagram_username:  goofy
linkedin_username: jagjitkumar

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
